{"name":"ABC BANKING CORPORATION LTD","local_address":"LEVEL 16, NEXXUS BUILDING, 41 CONNAUGHT ROAD CENTRAL, HONG KONG","principle_address":"7 DUKE OF EDINBURGH AVENUE, PLACE D' ARMES, 11328, PORT LOUIS, MAURITIUS","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"ABN AMRO BANK N.V.","local_address":"UNITS 7001-06 & 7008B, LEVEL 70, INTERNATIONAL COMMERCE CENTRE, 1 AUSTIN ROAD WEST, KOWLOON, HONG KONG.","principle_address":"GUSTAV MAHLERLAAN 10 1082PP AMSTERDAM THE NETHERLANDS","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"AGRICULTURAL BANK OF CHINA LIMITED","local_address":"25/F, AGRICULTURAL BANK OF CHINA TOWER, 50 CONNAUGHT ROAD CENTRAL, HONG KONG.","principle_address":"NO. 69, JIANGUOMEN NEI AVENUE, DONGCHENG DISTRICT, BEIJING, P.R. CHINA","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100235"}
{"name":"AIRSTAR BANK LIMITED","local_address":"SUITES 3201-07, 32/F, TOWER 5, THE GATEWAY, HARBOUR CITY, TSIM SHA TSUI, KOWLOON","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":null}
{"name":"ALLIED BANKING CORPORATION (HONG KONG) LIMITED","local_address":"1402 WORLD-WIDE HOUSE, 19 DES VOEUX ROAD CENTRAL, HONG KONG.","principle_address":null,"type":"Restricted Licence Bank","secstaff_reg_url":null}
{"name":"ANT BANK (HONG KONG) LIMITED","local_address":"SUITES 2312-13, 23/F, TOWER ONE, TIMES SQUARE, 1 MATHESON STREET, CAUSEWAY BAY, HONG KONG","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":null}
{"name":"ASHIKAGA BANK, LTD. (THE)","local_address":"SUITE 1601, 16/F, TOWER 2, THE GATEWAY, HARBOUR CITY, TSIM SHA TSUI, KOWLOON","principle_address":"1-25 SAKURA 4-CHOME, UTSUNOMIYA, TOCHIGI PREFECTURE 320-8610, JAPAN.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"AUSTRALIA AND NEW ZEALAND BANKING GROUP LIMITED","local_address":"20/F-22/F, THREE EXCHANGE SQUARE, 8 CONNAUGHT PLACE, CENTRAL, HONG KONG.","principle_address":"100 QUEEN STREET, MELBOURNE, VICTORIA 3000, AUSTRALIA.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100164"}
{"name":"BANC OF AMERICA SECURITIES ASIA LIMITED","local_address":"52/F, CHEUNG KONG CENTER, 2 QUEEN'S ROAD CENTRAL, CENTRAL, HONG KONG.","principle_address":null,"type":"Restricted Licence Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=200017"}
{"name":"BANCO BILBAO VIZCAYA ARGENTARIA S.A.","local_address":"UNIT 9507, LEVEL 95, INTERNATIONAL COMMERCE CENTRE, 1 AUSTIN ROAD WEST, KOWLOON.","principle_address":"CARRERA DE SAN JERONIMO, 36 28014 MADRID, SPAIN.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100157"}
{"name":"BANCO BPM SOCIETA' PER AZIONI","local_address":"SUITE 3205, CENTRAL PLAZA, 18 HARBOUR ROAD, WAN CHAI, HONG KONG.","principle_address":"PIAZZA NOGARA 2, 37100 VERONA, ITALY.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"BANCO BRADESCO S.A.","local_address":"SUITE 3516, TWO INTERNATIONAL FINANCE CENTRE, 8 FINANCE STREET, CENTRAL, HONG KONG","principle_address":"CIDADE DE DEUS, S/N, VILA YARA, OSASCO, SP, CEP 06029-900, BRAZIL","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"BANCO SANTANDER, S.A.","local_address":"10/F, TWO INTERNATIONAL FINANCE CENTRE, 8 FINANCE STREET, CENTRAL, HONG KONG.","principle_address":"PASEO DE PEREDA 9-12, SANTANDER, 39004, SPAIN.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100289"}
{"name":"BANCO SECURITY","local_address":"SUITE 2407, 9 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":"AV. APOQUINDO 3150, LAS CONDES, SANTIAGO, CHILE.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"BANGKOK BANK PUBLIC COMPANY LIMITED","local_address":"BANGKOK BANK BUILDING, 28 DES VOEUX ROAD, CENTRAL, HONG KONG.","principle_address":"333 SILOM ROAD, BANGKOK 10500, THAILAND.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"BANK J. SAFRA SARASIN AG","local_address":"40/F, EDINBURGH TOWER, THE LANDMARK, 15 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":"ELISABETHENSTRASSE 62, POSTFACH, CH-4002 BASEL, SWITZERLAND.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100297"}
{"name":"BANK JULIUS BAER & CO. LTD.","local_address":"39/F, ONE INTERNATIONAL FINANCE CENTRE, 1 HARBOUR VIEW STREET, CENTRAL, HONG KONG.","principle_address":"BAHNHOFSTRASSE 36, CH-8010 ZURICH, SWITZERLAND.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100301"}
{"name":"BANK OF AMERICA, NATIONAL ASSOCIATION","local_address":"52/F, CHEUNG KONG CENTER, 2 QUEEN'S ROAD CENTRAL, CENTRAL, HONG KONG.","principle_address":"100 NORTH TRYON STREET, 18/F, CHARLOTTE, NORTH CAROLINA 28255.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100045"}
{"name":"BANK OF BEIJING CO., LTD.","local_address":"UNIT 5601, 56/F, THE CENTER, NO. 99 QUEEN'S ROAD CENTRAL, HONG KONG","principle_address":"GROUND FLOOR, JIA NO.17, FINANCIAL STREET, XICHENG DISTRICT, BEIJING, PRC.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"BANK OF CHINA (HONG KONG) LIMITED","local_address":"14TH FLOOR, BANK OF CHINA TOWER, NO.1 GARDEN ROAD, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100072"}
{"name":"BANK OF CHINA INTERNATIONAL LIMITED","local_address":"2/F & 3/F, BANK OF CHINA BUILDING, 2A DES VOEUX ROAD CENTRAL, HONG KONG","principle_address":null,"type":"Restricted Licence Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=200069"}
{"name":"BANK OF CHINA LIMITED","local_address":"7/F, BANK OF CHINA TOWER, 1 GARDEN ROAD, CENTRAL, HONG KONG.","principle_address":"1 FUXINGMEN NEI DAJIE, BEIJING 100818, CHINA.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100011"}
{"name":"BANK OF COMMUNICATIONS (HONG KONG) LIMITED","local_address":"UNIT B B/F & G/F, UNIT C G/F, 1-3/F, 16/F ROOM 01 & 18/F, WHEELOCK HOUSE, 20 PEDDER STREET, CENTRAL, HONG KONG","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100320"}
{"name":"BANK OF COMMUNICATIONS CO., LTD.","local_address":"UNIT B B/F & G/F, UNIT C G/F, 1-3/F, 16/F ROOM 01 & 18/F, WHEELOCK HOUSE, 20 PEDDER STREET, CENTRAL, HONG KONG","principle_address":"NO.188 YINCHENG ZHONG ROAD, SHANGHAI, P R CHINA.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100023"}
{"name":"BANK OF DONGGUAN CO., LTD.","local_address":"SUITES 2504-2511, 25/F, TWO INTERNATIONAL FINANCE CENTRE, 8 FINANCE STREET, CENTRAL, HONG KONG","principle_address":"NO. 21 TIYU ROAD, GUANCHENG DISTRICT, DONGGUAN, GUANGDONG, CHINA.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"BANK OF EAST ASIA, LIMITED (THE)","local_address":"BANK OF EAST ASIA BUILDING, 10 DES VOEUX ROAD CENTRAL, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100013"}
{"name":"BANK OF FUKUOKA, LTD. (THE)","local_address":"ROOM 404, 4TH FLOOR, FAR EAST FINANCE CENTRE, 16 HARCOURT ROAD, HONG KONG.","principle_address":"13-1,TENJIN 2-CHOME, CHUO-KU,FUKUOKA 810-0001, JAPAN.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"BANK OF INDIA","local_address":"2/F., RUTTONJEE HOUSE, 11 DUDDELL STREET, CENTRAL, HONG KONG.","principle_address":"EXPRESS TOWERS NARIMAN POINT BOMBAY 400021, INDIA.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"BANK OF KYOTO, LTD. (THE)","local_address":"UNIT 2001, 20/F, TOWER 1, ADMIRALTY CENTRE, 18 HARCOURT ROAD, HONG KONG","principle_address":"700 YAKUSHIMAE-CHO, KARASUMADORI-MATSUBARA-AGARU SHIMOGYO-KU KYOTO, JAPAN.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"BANK OF MONTREAL","local_address":"SUITES 2806-2809, LEVEL 28, THREE PACIFIC PLACE, 1 QUEEN'S ROAD EAST, HONG KONG","principle_address":"129, RUE SAINT-JACQUES, MONTREAL, QUEBEC, H2Y 1L6, CANADA.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100097"}
{"name":"BANK OF NEW YORK MELLON (THE)","local_address":"LEVEL 26, THREE PACIFIC PLACE, 1 QUEEN'S ROAD EAST, HONG KONG.","principle_address":"240 GREENWICH STREET, NEW YORK, NY 10286","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100147"}
{"name":"BANK OF NOVA SCOTIA (THE)","local_address":"SUITE 2101 & 2401, CENTRAL TOWER, 28 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":"44 KING STREET WEST, TORONTO, ONTARIO, CANADA.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100088"}
{"name":"BANK OF SHANGHAI (HONG KONG) LIMITED","local_address":"34/F, CHAMPION TOWER, 3 GARDEN ROAD, CENTRAL, HONG KONG.","principle_address":null,"type":"Restricted Licence Bank","secstaff_reg_url":null}
{"name":"BANK OF SINGAPORE LIMITED","local_address":"34/F & 35/F, ONE INTERNATIONAL FINANCE CENTRE, 1 HARBOUR VIEW STREET, CENTRAL, HONG KONG.","principle_address":"63 CHULIA STREET, #10-00 OCBC CENTRE EAST, SINGAPORE (049514)","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100290"}
{"name":"BANK OF TAIWAN","local_address":"23/F, CENTRAL TOWER, 28 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":"NO. 120, SECTION 1, CHONGCING SOUTH ROAD, JHONGJHENG DISTRICT, TAIPEI CITY 10007, TAIWAN.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"BANK OF YOKOHAMA, LTD. (THE)","local_address":"SUITE 2109 , TOWER 6, THE GATEWAY, HARBOUR CITY, 9 CANTON ROAD, TSIM SHA TSUI, KOWLOON.","principle_address":"1-1, MINATOMIRAI 3-CHOME, NISHI-KU, YOKOHAMA, KANAGAWA, 220-8611, JAPAN.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"BANK SINOPAC","local_address":"26/F, CENTRAL TOWER, 28 QUEEN'S ROAD CENTRAL, CENTRAL, HONG KONG.","principle_address":"NO.36, SECTION 3, NANKING EAST ROAD, CHUNG SHAN DISTRICT, TAIPEI 104, TAIWAN.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100260"}
{"name":"BANQUE CANTONALE DE GENEVE","local_address":"UNIT 1802-03, 18/F, ALEXANDRA HOUSE, NO. 18 CHATER ROAD, CENTRAL, HONG KONG.","principle_address":"BCGE, QUAI DE L'LLE 17, P.O. BOX 2251, CH-1211 GENEVA 2, SWITZERLAND.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"BANQUE PICTET & CIE SA","local_address":"9/F, CHATER HOUSE, 8 CONNAUGHT ROAD CENTRAL, HONG KONG","principle_address":"ROUTE DES ACACIAS 60, 1211 GENEVA 73, SWITZERLAND","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100339"}
{"name":"BANQUE TRANSATLANTIQUE S.A.","local_address":"SUITE 2201, 22/F, CENTRAL TOWER, 28 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":"26 AVENUE F.D. ROOSEVELT, 75008 PARIS, FRANCE","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"BARCLAYS BANK PLC","local_address":"41/F, CHEUNG KONG CENTER, 2 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":"1 CHURCHILL PLACE, LONDON, E14 5HP, UNITED KINGDOM.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100084"}
{"name":"BCOM FINANCE (HONG KONG) LIMITED","local_address":"1/F WHEELOCK HOUSE, 20 PEDDER STREET, CENTRAL, HONG KONG.","principle_address":null,"type":"Deposit-taking Company","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=300275"}
{"name":"BDO UNIBANK, INC.","local_address":"GROUND FLOOR, EURO TRADE CENTRE, 13-14 CONNAUGHT ROAD CENTRAL, HONG KONG.","principle_address":"BDO CORPORATE CENTER, 7899 MAKATI AVENUE, MAKATI CITY, PHILIPPINES.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100054"}
{"name":"BENDURA BANK AG","local_address":"UNIT 1905, LEVEL 19, INTERNATIONAL COMMERCE CENTRE, 1 AUSTIN ROAD WEST, KOWLOON","principle_address":"SCHAANER STRASSE 27, 9487 GAMPRIN-BENDERN, PRINCIPALITY OF LIECHTENSTEIN","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"BNP PARIBAS","local_address":"60-63/F, TWO INTERNATIONAL FINANCE CENTRE, 8 FINANCE STREET, CENTRAL, HONG KONG.","principle_address":"16, BOULEVARD DES ITALIENS, 75009 PARIS, FRANCE.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100079"}
{"name":"BPI INTERNATIONAL FINANCE LIMITED","local_address":"5/F, LHT TOWER, 31 QUEEN'S ROAD CENTRAL, HONG KONG","principle_address":null,"type":"Deposit-taking Company","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=300006"}
{"name":"CA INDOSUEZ (SWITZERLAND) SA","local_address":"SUITE 2918, 29/F, TWO PACIFIC PLACE, 88 QUEENSWAY, HONG KONG.","principle_address":"4, QUAI G-N-RAL-GUISAN, 1204 GENEVA, SWITZERLAND.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100303"}
{"name":"CAIXABANK S.A.","local_address":"UNIT 12A, 12TH FLOOR, NO. 33 DES VOEUX ROAD CENTRAL, CENTRAL, HONG KONG","principle_address":"PINTOR SOROLLA, 2-4 IN VALENCIA, SPAIN","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"CANADIAN IMPERIAL BANK OF COMMERCE","local_address":"SUITE 3602, 36/F., CHEUNG KONG CENTER, 2 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":"81 BAY STREET, CIBC SQUARE, TORONTO, ONTARIO, M5J 0E7 CANADA","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100099"}
{"name":"CATHAY BANK","local_address":"3008, 30/F, TOWER 2, THE GATEWAY, 25 CANTON ROAD, TSIM SHA TSUI, KOWLOON","principle_address":"777 NORTH BROADWAY, LOS ANGELES, CA 90012, U.S.A.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"CATHAY UNITED BANK COMPANY, LIMITED","local_address":"10/F, LEE GARDEN THREE, 1 SUNNING ROAD, CAUSEWAY BAY, HONG KONG","principle_address":"1/F, NO. 7, SONGREN ROAD, TAIPEI CITY 110, TAIWAN.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100252"}
{"name":"CHANG HWA COMMERCIAL BANK, LTD.","local_address":"1401, TOWER II, THE GATEWAY, 25 CANTON ROAD, KOWLOON.","principle_address":"NO. 38, SECTION 2, ZIYOU ROAD, CENTRAL DIST., TAICHUNG CITY, TAIWAN","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100223"}
{"name":"CHAU'S BROTHERS FINANCE COMPANY LIMITED","local_address":"6TH FLOOR, CHAU'S COMMERCIAL CENTRE, 284 SHA TSUI ROAD, TSUEN WAN, N.T.","principle_address":null,"type":"Deposit-taking Company","secstaff_reg_url":null}
{"name":"CHIBA BANK, LTD. (THE)","local_address":"UNIT 2510, ONE PACIFIC PLACE, 88 QUEENSWAY, CENTRAL, HONG KONG.","principle_address":"1-2, CHIBA-MINATO, CHUO-KU CHIBA, JAPAN.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"CHINA BOHAI BANK CO., LTD.","local_address":"SUITE 1201-1209 & 1215-1216, 12/F, TWO INTERNATIONAL FINANCE CENTRE, 8 FINANCE STREET, CENTRAL, HONG KONG","principle_address":"NO. 218, HAIHE EAST ROAD, HEDONG DISTRICT, TIANJIN, CHINA","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"CHINA CITIC BANK INTERNATIONAL LIMITED","local_address":"61-65, DES VOEUX ROAD CENTRAL, HONG KONG","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100040"}
{"name":"CHINA CONSTRUCTION BANK (ASIA) CORPORATION LIMITED","local_address":"28/F, CCB TOWER, NO. 3 CONNAUGHT ROAD CENTRAL, CENTRAL, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100015"}
{"name":"CHINA CONSTRUCTION BANK CORPORATION","local_address":"28/F, CCB TOWER, NO. 3 CONNAUGHT ROAD CENTRAL, CENTRAL, HONG KONG.","principle_address":"NO.25, FINANCIAL STREET, XICHENG DISTRICT, BEIJING, P.R. CHINA","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100234"}
{"name":"CHINA DEVELOPMENT BANK","local_address":"33/F, ONE INTERNATIONAL FINANCE CENTRE, NO.1 HARBOUR VIEW STREET, CENTRAL, HONG KONG.","principle_address":"NO. 18, FUXINGMENNEI STREET, XICHENG DISTRICT, BEIJING, P.R. CHINA","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"CHINA EVERBRIGHT BANK CO., LTD.","local_address":"G/F (SHOP B), 11/F, 20/F, 22/F, 23/F & 36/F, EVERBRIGHT CENTRE, 108 GLOUCESTER ROAD, WANCHAI, HONG KONG.","principle_address":"CHINA EVERBRIGHT CENTER, NO. 25 TAIPINGQIAO AVENUE, XICHENG DISTRICT, BEIJING, P.R. CHINA","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100314"}
{"name":"CHINA GUANGFA BANK CO., LTD.","local_address":"12 FLOOR, ONE EXCHANGE SQUARE, 8 CONNAUGHT PLACE, CENTRAL, HONG KONG","principle_address":"CGB BUILDING, NO. 713 DONGFENGDONG ROAD, YUEXIU DISTRICT, GUANGZHOU, GUANGDONG PROVINCE, P. R. CHINA","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"CHINA MERCHANTS BANK CO., LTD.","local_address":"27/F - 31/F, THREE EXCHANGE SQUARE, 8 CONNAUGHT PLACE, CENTRAL, HONG KONG.","principle_address":"CHINA MERCHANTS BANK TOWER, 7088 SHENNAN BOULEVARD, SHENZHEN, CHINA.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100255"}
{"name":"CHINA MINSHENG BANKING CORP., LTD.","local_address":"ROOMS 01-02, 12-16, 37/F & 40/F, TWO INTERNATIONAL FINANCE CENTRE, 8 FINANCE STREET, CENTRAL, HONG KONG","principle_address":"NO. 2, FUXINGMENNEI AVENUE, XICHENG DISTRICT, BEIJING, CHINA 100031.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100311"}
{"name":"CHINA ZHESHANG BANK CO., LTD.","local_address":"15TH FLOOR, THREE EXCHANGE SQUARE, NO. 8 CONNAUGHT PLACE, CENTRAL, HONG KONG","principle_address":"288 QING CHUN LU, HANGZHOU, ZHENJIANG, POSTCODE 310006, PEOPLE'S REPUBLIC OF CHINA","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100324"}
{"name":"CHIYU BANKING CORPORATION LIMITED","local_address":"74-78 DES VOEUX ROAD CENTRAL, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100064"}
{"name":"CHONG HING BANK LIMITED","local_address":"GROUND FLOOR, CHONG HING BANK CENTRE, 24 DES VOEUX ROAD CENTRAL, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100039"}
{"name":"CHONG HING FINANCE LIMITED","local_address":"GROUND FLOOR, CHONG HING BANK CENTRE, 24 DES VOEUX ROAD CENTRAL, HONG KONG.","principle_address":null,"type":"Deposit-taking Company","secstaff_reg_url":null}
{"name":"CHUGOKU BANK, LTD (THE)","local_address":"ROOMS 601 & 609-610, 6TH FLOOR, GLOUCESTER TOWER, THE LANDMARK, 15 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":"1-15-20, MARUNOUCHI, KITA-KU, OKAYAMA, JAPAN.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"CIMB BANK BERHAD","local_address":"ROOMS 2501 AND 2507-2510, 25/F, GLOUCESTER TOWER, THE LANDMARK, 15 QUEEN'S ROAD CENTRAL, HONG KONG","principle_address":"LEVEL 17, MENARA CIMB, JALAN STESEN SENTRAL 2, KUALA LUMPUR SENTRAL, 50470 KUALA LUMPUR, MALAYSIA","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100315"}
{"name":"CITIBANK (HONG KONG) LIMITED","local_address":"CITI TOWER, ONE BAY EAST, NO. 83 HOI BUN ROAD, KWUN TONG, KOWLOON","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100270"}
{"name":"CITIBANK, N.A.","local_address":"50TH FLOOR, CHAMPION TOWER, 3 GARDEN ROAD, CENTRAL, HONG KONG.","principle_address":"388 GREENWICH STREET, NEW YORK, NY 10013, USA","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100008"}
{"name":"CITICORP INTERNATIONAL LIMITED","local_address":"50TH FLOOR, CHAMPION TOWER, 3 GARDEN ROAD, CENTRAL, HONG KONG.","principle_address":null,"type":"Restricted Licence Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=200036"}
{"name":"CLEARSTREAM BANKING S.A.","local_address":"2904-7, 29/F, MAN YEE BUILDING, 68 DES VOEUX ROAD CENTRAL, HONG KONG.","principle_address":"42 AVENUE JF KENNEDY, L-1855 LUXEMBOURG.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"CMB WING LUNG BANK LIMITED","local_address":"43-49 DES VOEUX ROAD CENTRAL, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100042"}
{"name":"COMMERZBANK AG","local_address":"ROOM 1502, 15/F, LEE GARDEN ONE, 33 HYSAN AVENUE, CAUSEWAY BAY, HONG KONG.","principle_address":"KAISERSTR. 16, 60311 FRANKFURT AM MAIN, GERMANY","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"COMMONWEALTH BANK OF AUSTRALIA","local_address":"SUITE 1401, ONE EXCHANGE SQUARE, 8 CONNAUGHT PLACE, CENTRAL, HONG KONG.","principle_address":"COMMONWEALTH BANK PLACE SOUTH, LEVEL 1, 11 HARBOUR STREET, SYDNEY NSW 2000, AUSTRALIA","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100165"}
{"name":"COMMONWEALTH FINANCE CORPORATION LIMITED","local_address":"11/F., WYNDHAM PLACE, 40-44 WYNDHAM STREET, CENTRAL, HONG KONG.","principle_address":null,"type":"Deposit-taking Company","secstaff_reg_url":null}
{"name":"COÖPERATIEVE RABOBANK U.A.","local_address":"13/F, ONE PACIFIC PLACE, 88 QUEENSWAY, HONG KONG","principle_address":"CROESELAAN 18, 3521 CB UTRECHT, THE NETHERLANDS.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100197"}
{"name":"CORPORATE FINANCE (D.T.C.) LIMITED","local_address":"UNIT 404A, 4/F, FORTRESS TOWER, 250 KING'S ROAD, NORTH POINT, HONG KONG","principle_address":null,"type":"Deposit-taking Company","secstaff_reg_url":null}
{"name":"CREDIT AGRICOLE CORPORATE AND INVESTMENT BANK","local_address":"SUITES 2506-2515, 26-27/F & 30/F, TWO PACIFIC PLACE, 88 QUEENSWAY, HONG KONG.","principle_address":"12, PLACE DES ETATS UNIS - CS 70052-92547 MONTROUGE CEDEX, FRANCE","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100086"}
{"name":"CREDIT INDUSTRIEL ET COMMERCIAL","local_address":"SUITE 2201, 22/F, CENTRAL TOWER, 28 QUEEN'S ROAD CENTRAL, HONG KONG","principle_address":"6 AVENUE DE PROVENCE, 75009 PARIS, FRANCE.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100322"}
{"name":"CREDIT SUISSE AG","local_address":"LEVEL 88, INTERNATIONAL COMMERCE CENTRE, 1 AUSTIN ROAD WEST, KOWLOON.","principle_address":"PARADEPLATZ 8, CH-8001 ZURICH, SWITZERLAND.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100248"}
{"name":"CTBC BANK CO., LTD.","local_address":"ROOM 2104-10, 21/F AND ROOM 2801, 28/F, TWO INTERNATIONAL FINANCE CENTRE, 8 FINANCE STREET, CENTRAL, HONG KONG.","principle_address":"NO. 166, NO. 168, NO. 170, JINGMAO 2ND ROAD, NANGANG DISTRICT, TAIPEI, TAIWAN.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100242"}
{"name":"DAH SING BANK, LIMITED","local_address":"26/F, DAH SING FINANCIAL CENTRE, 248 QUEEN'S ROAD EAST, WAN CHAI, HONG KONG","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100006"}
{"name":"DBS BANK (HONG KONG) LIMITED","local_address":"11TH FLOOR, THE CENTER, 99 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100034"}
{"name":"DBS BANK LTD.","local_address":"18TH FLOOR, THE CENTER, 99 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":"12 MARINA BOULEVARD, MARINA BAY FINANCIAL CENTRE TOWER 3, SINGAPORE 018982.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100199"}
{"name":"DEUTSCHE BANK AKTIENGESELLSCHAFT","local_address":"60/F, INTERNATIONAL COMMERCE CENTRE, 1 AUSTIN ROAD WEST, KOWLOON.","principle_address":"TAUNUSANLAGE 12, 60325 FRANKFURT, FEDERAL REPUBLIC OF GERMANY.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100085"}
{"name":"DUKASCOPY BANK SA","local_address":"ROOM 701, 7/F, TOWER 2, SILVERCORD, 30 CANTON ROAD, TSIM SHA TSUI, KOWLOON.","principle_address":"ROUTEDE PRE-BOIS 20, CH-1215 GENEVA 15, SWITZERLAND.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"DZ BANK AG DEUTSCHE ZENTRAL-GENOSSENSCHAFTSBANK, FRANKFURT AM MAIN","local_address":"9/F., ADMIRALTY CENTRE, TOWER II, 18 HARCOURT ROAD, HONG KONG.","principle_address":"AM PLATZ DER REPUBLIK, 60325 FRANKFURT AM MAIN, GERMANY.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"E.SUN COMMERCIAL BANK, LTD.","local_address":"SUITES 2701, 2710-14, 27/F AND 28/F, TOWER 6, THE GATEWAY, 9 CANTON ROAD, TSIMSHATSUI, KOWLOON.","principle_address":"NO. 117, SEC.3, MINSHENG E. ROAD, SONGSHAN DISTRICT, TAIPEI CITY 105-46, TAIWAN","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100264"}
{"name":"EAST WEST BANK","local_address":"SUITE 1108, 11/F, TWO INTERNATIONAL FINANCE CENTRE, 8 FINANCE STREET, CENTRAL, HONG KONG.","principle_address":"135N. LOS ROBLES AVE., 7TH FLOOR, PASADENA, CA 91101 UNITED STATES.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100278"}
{"name":"EFG BANK AG","local_address":"LEVEL 18, INTERNATIONAL COMMERCE CENTRE, 1 AUSTIN ROAD WEST, KOWLOON.","principle_address":"BLEICHERWEG 8, 8001 ZURICH, SWITZERLAND.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100254"}
{"name":"ERSTE GROUP BANK AG","local_address":"UNITS 08 TO 13, 3RD FLOOR, FAR EAST FINANCE CENTRE, 16 HARCOURT ROAD, ADMIRALTY, HONG KONG","principle_address":"AM BELVEDERE 1, 1100 WIEN, AUSTRIA","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"EUROCLEAR BANK","local_address":"20/F, CENTRAL PLAZA, 18 HARBOUR ROAD, WANCHAI, HONG KONG.","principle_address":"1, BOULEVARD DU ROI ALBERT II, B-1210 BRUSSELS, BELGIUM.","type":"Restricted Licence Bank","secstaff_reg_url":null}
{"name":"EXPORT-IMPORT BANK OF CHINA (THE)","local_address":"ROOM 5707, 57/F, TWO INTERNATIONAL FINANCE CENTRE, 8 FINANCE STREET, CENTRAL, HONG KONG","principle_address":"NO. 30 FUXINGMENNEI STREET, XICHENG DISTRICT, BEIJING, 10031, CHINA","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"FAR EASTERN INTERNATIONAL BANK","local_address":"20TH FLOOR, 8 QUEEN'S ROAD CENTRAL, CENTRAL, HONG KONG.","principle_address":"26-27 FLOOR, TUN HWA S. ROAD, SECTION 2, TAIPEI, TAIWAN.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"FIRST ABU DHABI BANK PJSC","local_address":"SUITES 705-8, ICBC TOWER, 3 GARDEN ROAD, CENTRAL, HONG KONG","principle_address":"FAB BUILDING, KHALIFA BUSINESS PARK, AL QURM, ABU DHABI, UNITED ARAB EMIRATES, P.O. BOX 6316","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"FIRST COMMERCIAL BANK, LTD.","local_address":"1702-8, 17TH FLOOR, PRUDENTIAL TOWER, THE GATEWAY, HARBOUR CITY, 21 CANTON ROAD, TSIMSHATSUI, KOWLOON","principle_address":"30 CHUNGKING S. ROAD, SECTION 1, TAIPEI 100, TAIWAN.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100220"}
{"name":"FUBON BANK (HONG KONG) LIMITED","local_address":"FUBON BANK BUILDING, 38 DES VOEUX ROAD CENTRAL, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100138"}
{"name":"FUBON CREDIT (HONG KONG) LIMITED","local_address":"ROOM 2501, 25/F, WING ON HOUSE, 71 DES VOEUX ROAD CENTRAL, HONG KONG","principle_address":null,"type":"Deposit-taking Company","secstaff_reg_url":null}
