{"name":"FAR EASTERN INTERNATIONAL BANK","local_address":"20TH FLOOR, 8 QUEEN'S ROAD CENTRAL, CENTRAL, HONG KONG.","principle_address":"26-27 FLOOR, TUN HWA S. ROAD, SECTION 2, TAIPEI, TAIWAN.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"FIRST ABU DHABI BANK PJSC","local_address":"SUITES 705-8, ICBC TOWER, 3 GARDEN ROAD, CENTRAL, HONG KONG","principle_address":"FAB BUILDING, KHALIFA BUSINESS PARK, AL QURM, ABU DHABI, UNITED ARAB EMIRATES, P.O. BOX 6316","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"FIRST COMMERCIAL BANK, LTD.","local_address":"1702-8, 17TH FLOOR, PRUDENTIAL TOWER, THE GATEWAY, HARBOUR CITY, 21 CANTON ROAD, TSIMSHATSUI, KOWLOON","principle_address":"30 CHUNGKING S. ROAD, SECTION 1, TAIPEI 100, TAIWAN.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100220"}
{"name":"FUBON BANK (HONG KONG) LIMITED","local_address":"FUBON BANK BUILDING, 34-38 DES VOEUX ROAD CENTRAL, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100138"}
{"name":"FUBON CREDIT (HONG KONG) LIMITED","local_address":"ROOM 2501, 25/F, WING ON HOUSE, 71 DES VOEUX ROAD CENTRAL, HONG KONG","principle_address":null,"type":"Deposit-taking Company","secstaff_reg_url":null}
{"name":"FUSION BANK LIMITED","local_address":"2/F, INNOCENTRE, 72 TAT CHEE AVENUE, KOWLOON TONG, KOWLOON","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":null}
{"name":"GOLDMAN SACHS ASIA BANK LIMITED","local_address":"68/F, CHEUNG KONG CENTER, 2 QUEEN'S ROAD CENTRAL, HONG KONG","principle_address":null,"type":"Restricted Licence Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=200109"}
{"name":"GUNMA BANK, LTD. (THE)","local_address":"SUITE 1803, TOWER 1, THE GATEWAY, HARBOUR CITY, 25 CANTON ROAD, TSIM SHA TSUI, KOWLOON","principle_address":"194, MOTOSOJAMACHI, MAEBASHI, GUNMA 371-8611, JAPAN","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"HABIB BANK A.G. ZURICH","local_address":"ROOM 1701-1705, WING ON HOUSE, 71 DES VOEUX ROAD, CENTRAL, HONG KONG.","principle_address":"WEINBERGSTRASSE 59, P.O. BOX. 4931, 8022 ZURICH, SWITZERLAND.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"HABIB BANK ZURICH (HONG KONG) LIMITED","local_address":"1701-1705, WING ON HOUSE, 71 DES VOEUX ROAD, CENTRAL, HONG KONG.","principle_address":null,"type":"Restricted Licence Bank","secstaff_reg_url":null}
{"name":"HACHIJUNI BANK, LTD. (THE)","local_address":"SUITES 1602-1605, 16/F, TOWER 2, THE GATEWAY, HARBOUR CITY, 25 CANTON ROAD, KOWLOON.","principle_address":"178-8, OKADA, NAGANO, JAPAN.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"HANG SENG BANK, LIMITED","local_address":"HANG SENG BANK BLDG., 83 DES VOEUX ROAD CENTRAL, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100057"}
{"name":"HDFC BANK LIMITED","local_address":"SUITE 1707, 17/F, TOWER 1, THE GATEWAY, HARBOUR CITY, 25 CANTON ROAD, TSIM SHA TSUI, KOWLOON.","principle_address":"HDFC BANK HOUSE, SENAPATI BAPAT MARG, LOWER PAREL, MUMBAI 400 013, INDIA","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"HONG LEONG BANK BERHAD","local_address":"50TH FLOOR, THE CENTER, 99 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":"LEVEL 30, MENARA HONG LEONG, NO. 6, JALAN DAMANLELA, BUKIT DAMANSARA, 50490 KUALA LUMPUR, MALAYSIA","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100268"}
{"name":"HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED (THE)","local_address":"1 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100002"}
{"name":"HSBC BANK PLC","local_address":"LEVEL 18, HSBC MAIN BUILDING, NO. 1 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":"8 CANADA SQUARE, LONDON, E14 5HQ, UNITED KINGDOM.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100249"}
{"name":"HSBC BANK USA, NATIONAL ASSOCIATION","local_address":"1 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":"1800 TYSONS BOULEVARD, SUITE 50, MCLEAN, VIRGINIA 220102, U.S.A.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"HUA NAN COMMERCIAL BANK, LTD.","local_address":"SUITE 5601-03, 56/F., CENTRAL PLAZA, 18 HARBOUR ROAD, WANCHAI, HONG KONG.","principle_address":"NO. 123, SONGREN ROAD, XINYI DIST., TAIPEI, TAIWAN.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100213"}
{"name":"HUA XIA BANK CO., LIMITED","local_address":"18/F, TWO INTERNATIONAL FINANCE CENTRE, 8 FINANCE STREET, CENTRAL, HONG KONG","principle_address":"HUA XIA BANK MANSION, 22 JIANGUOMENNEI STREET, DONGCHENG DISTRICT, BEIJING, P.R. CHINA","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100334"}
{"name":"ICICI BANK LIMITED","local_address":"UNIT 1504B-1505, LEVEL 15, INTERNATIONAL COMMERCE CENTRE, 1 AUSTIN ROAD WEST, KOWLOON.","principle_address":"ICICI BANK TOWERS, BANDRA-KURLA COMPLEX, MUMBAI 400 051, INDIA","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100271"}
{"name":"INDIAN OVERSEAS BANK","local_address":"3/F., RUTTONJEE HOUSE, 11 DUDDELL STREET, CENTRAL, HONG KONG.","principle_address":"762,ANNA SALAI MADRAS-6000002, INDIA.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"INDUSTRIAL AND COMMERCIAL BANK OF CHINA (ASIA) LIMITED","local_address":"33/F, ICBC TOWER, 3 GARDEN ROAD, CENTRAL, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100077"}
{"name":"INDUSTRIAL AND COMMERCIAL BANK OF CHINA LIMITED","local_address":"33/F., ICBC TOWER, 3 GARDEN ROAD, CENTRAL, HONG KONG.","principle_address":"55 FUXINGMENNEI DAJIE, XICHENG DISTRICT, BEIJING, 100031, CHINA.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"INDUSTRIAL BANK CO., LTD.","local_address":"10-12/F, ONE INTERNATIONAL FINANCE CENTRE, 1 HARBOUR VIEW STREET, CENTRAL, HONG KONG","principle_address":"154 HUDONG ROAD, FUZHOU, PR CHINA","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100317"}
{"name":"INDUSTRIAL BANK OF KOREA","local_address":"SUITE 3113, 31ST FLOOR, TWO PACIFIC PLACE, 88 QUEENSWAY, HONG KONG.","principle_address":"50,ULCHIRO 2-GA, CHUNG-GU, SEOUL 100-758, KOREA.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"ING BANK N.V.","local_address":"8TH FLOOR, THREE PACIFIC PLACE, 1 QUEEN'S ROAD EAST, HONG KONG","principle_address":"BIJLMERDREEF 106, 1102 CT AMSTERDAM, THE NETHERLANDS","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100155"}
{"name":"INTESA SANPAOLO SPA","local_address":"UNITS 8102-05 & 8106A, LEVEL 81, INTERNATIONAL COMMERCE CENTRE, 1 AUSTIN ROAD WEST, KOWLOON.","principle_address":"VIA MONTE DI PIETA, 8-20121 MILANO, ITALY.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100243"}
{"name":"IYO BANK, LTD. (THE)","local_address":"SUITE 2812, TOWER TWO, TIMES SQUARE, 1 MATHESON STREET, CAUSEWAY BAY, HONG KONG","principle_address":"1, MINAMI-HORIBATA-CHO, MATSUYAMA CITY, EHIME PREF.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"J.P. MORGAN SECURITIES (ASIA PACIFIC) LIMITED","local_address":"18/F, 23-29/F, CHATER HOUSE, 8 CONNAUGHT ROAD CENTRAL, HONG KONG","principle_address":null,"type":"Restricted Licence Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=200033"}
{"name":"JIH SUN INTERNATIONAL BANK, LTD.","local_address":"UNIT 906, 9/F, TWO HARBOURFRONT, 22 TAK FUNG STREET, HUNGHOM, KOWLOON","principle_address":"1F, NO. 10, SECTION 1, CHONGQING SOUTH ROAD, ZHONGZHENG DISTRICT, TAIPEI CITY, TAIWAN.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"JPMORGAN CHASE BANK, NATIONAL ASSOCIATION","local_address":"18/F, 20/F, 22-29/F, CHATER HOUSE, 8 CONNAUGHT ROAD CENTRAL, HONG KONG","principle_address":"383 MADISON AVENUE, NEW YORK, NY 10179, UNITED STATES.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100089"}
{"name":"KASIKORNBANK PUBLIC COMPANY LIMITED","local_address":"UNIT 3316, 33/F, CHINA MERCHANTS TOWER, SHUN TAK CENTRE, NO. 168-200 CONNAUGHT ROAD CENTRAL, HONG KONG.","principle_address":"1 SOI RAT BURANA 27/1 RAT BURANA ROAD, RAT BURANA DISTRICT, BANGKOK 10140, THAILAND","type":"Restricted Licence Bank","secstaff_reg_url":null}
{"name":"KBC BANK N.V.","local_address":"39/F., CENTRAL PLAZA, 18 HARBOUR ROAD, HONG KONG.","principle_address":"HAVENLAAN 2, (SINT-JANS-MOLENBEEK) 1080 BRUSSELS, BELGIUM","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"KDB ASIA LIMITED","local_address":"SUITE 2005-8, 20TH FLOOR, TWO INTERNATIONAL FINANCE CENTRE, 8 FINANCE STREET, CENTRAL, HONG KONG.","principle_address":null,"type":"Restricted Licence Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=200065"}
{"name":"KEB HANA BANK","local_address":"UNIT 6201, LEVEL 62, INTERNATIONAL COMMERCE CENTRE, 1 AUSTIN ROAD WEST, KOWLOON","principle_address":"35, EULJI-RO, JUNG-GU, SEOUL, REPUBLIC OF KOREA","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100080"}
{"name":"KEB HANA GLOBAL FINANCE LIMITED","local_address":"UNIT 6203A, LEVEL 62, INTERNATIONAL COMMERCE CENTRE, 1 AUSTIN ROAD WEST, KOWLOON","principle_address":null,"type":"Deposit-taking Company","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=300506"}
{"name":"KEXIM ASIA LIMITED","local_address":"UNIT 2904-05, 29/F, CENTRAL PLAZA, 18 HARBOUR ROAD, WANCHAI, HONG KONG.","principle_address":null,"type":"Deposit-taking Company","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=300504"}
{"name":"KOOKMIN BANK","local_address":"SUITE 1101 AND 1106, 11TH FLOOR, CENTRAL PLAZA, 18 HARBOUR ROAD, WANCHAI, HONG KONG","principle_address":"#26, GUKJEGEUMYUNG-RO 8-GIL, YEONGDEUNGPO-GU, SEOUL, REPUBLIC OF KOREA","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100323"}
{"name":"KOREA DEVELOPMENT BANK (THE)","local_address":"SUITES 2005-2008, 20TH FLOOR, TWO INTERNATIONAL FINANCE CENTRE, 8 FINANCE STREET, CENTRAL, HONG KONG.","principle_address":"14 EUNHAENG-RO, YEONGDEUNGPO-GU, SEOUL, 150-973, KOREA.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"LAND BANK OF TAIWAN CO., LTD.","local_address":"UNIT 3101-06 & 12, TOWER 1, THE GATEWAY, NO. 25 CANTON ROAD, TSIM SHA TSUI, KOWLOON","principle_address":"46 GUANCIAN ROAD, JHONGJHEN DISTRICT, TAIPEI CITY, TAIWAN.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"LGT BANK AG","local_address":"SUITE 4203, TWO EXCHANGE SQUARE, 8 CONNAUGHT PLACE, HONG KONG.","principle_address":"HERRENGASSE 12, FL-9490 VADUZ, LIECHTENSTEIN.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100305"}
{"name":"LIVI BANK LIMITED","local_address":"28TH FLOOR, OXFORD HOUSE, TAIKOO PLACE, 979 KING'S ROAD, QUARRY BAY, HONG KONG","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":null}
{"name":"MACQUARIE BANK LIMITED","local_address":"SUITES 1801-04 & 1815-16, SUITES 2001-02 & 2016, LEVEL 22-23, ONE INTERNATIONAL FINANCE CENTRE, 1 HARBOUR VIEW STREET,CENTRAL, HONG KONG","principle_address":"50 MARTIN PLACE, SYDNEY, NSW 2000, AUSTRALIA.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"MALAYAN BANKING BERHAD","local_address":"29/F, LEE GARDEN THREE, 1 SUNNING ROAD, CAUSEWAY BAY, HONG KONG","principle_address":"MENARA MAYBANK,100 JALAN TUN PERAK, 50050 KUALA LUMPUR, MALAYSIA.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100050"}
{"name":"MANULIFE BANK OF CANADA","local_address":"21/F, MANULIFE TOWER, ONE BAY EAST, 83 HOI BUN ROAD, KWUN TONG, KOWLOON","principle_address":"500 KING STREET NORTH, BOX 1602, WATERLOO, ON N2J 4C6, CANADA","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"MASHREQ BANK - PUBLIC SHAREHOLDING COMPANY","local_address":"UNIT 05-09, 27/F, PROSPERITY MILLENNIA PLAZA, 663 KING'S ROAD, NORTH POINT, HONG KONG","principle_address":"POST BOX 1250, DUBAI, UNITED ARAB EMIRATES","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"MEGA INTERNATIONAL COMMERCIAL BANK CO., LTD.","local_address":"SUITE 2201, 22/F., PRUDENTIAL TOWER, THE GATEWAY, HARBOUR CITY, 21 CANTON ROAD, KOWLOON.","principle_address":"100, CHI LIN ROAD, TAIPEI (104), TAIWAN.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100261"}
{"name":"MELLI BANK PLC","local_address":"SUITE 2010-2011, 20/F, CHAMPION TOWER, 3 GARDEN ROAD, CENTRAL, HONG KONG","principle_address":"98A KENSINGTON HIGH STREET, LONDON, W8 4SG, UNITED KINGDOM","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"METROPOLITAN BANK AND TRUST COMPANY","local_address":"UNIT D, 15/F., UNITED CENTRE, 95 QUEENSWAY, HONG KONG.","principle_address":"SEN. GIL J. PUYAT AVE., MAKATI CITY, METRO MANILA, PHILIPPINES 1200.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"MITSUBISHI UFJ TRUST AND BANKING CORPORATION","local_address":"SUITES 2102-7, TOWER 6, THE GATEWAY, HARBOUR CITY, 9 CANTON ROAD, TSIM SHA TSUI, KOWLOON.","principle_address":"1-4-5, MARUNOUCHI, CHIYODA-KU, TOKYO 100-8212, JAPAN.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"MIZUHO BANK, LTD.","local_address":"12/F, K11 ATELIER, 18 SALISBURY ROAD, TSIM SHA TSUI, KOWLOON","principle_address":"OTEMACHI TOWER, 1-5-5, OTEMACHI, CHIYODA-KU, TOKYO, JAPAN.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"MORGAN STANLEY BANK ASIA LIMITED","local_address":"LEVEL 31, INTERNATIONAL COMMERCE CENTRE, 1 AUSTIN ROAD WEST, KOWLOON.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100335"}
{"name":"MOX BANK LIMITED","local_address":"39/F, OXFORD HOUSE, TAIKOO PLACE, 979 KING'S ROAD, QUARRY BAY, HONG KONG","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":null}
{"name":"MUFG BANK, LTD.","local_address":"8/F, AIA CENTRAL, 1 CONNAUGHT ROAD CENTRAL, CENTRAL, HONG KONG.","principle_address":"7-1 MARUNOUCHI 2-CHOME, CHIYODA-KU, TOKYO 100 JAPAN.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100133"}
{"name":"NANYANG COMMERCIAL BANK, LIMITED","local_address":"NANYANG COMMERCIAL BANK BUILDING, 151 DES VOEUX ROAD CENTRAL, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100060"}
{"name":"NATIONAL AUSTRALIA BANK LIMITED","local_address":"SUITES 506-509 ON LEVEL 5 & LEVEL 6, THREE PACIFIC PLACE, 1 QUEEN'S ROAD EAST, HONG KONG","principle_address":"LEVEL 34, 500 BOURKE STREET MELBOURNE VIC 3000, AUSTRALIA.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100166"}
{"name":"NATIONAL BANK OF CANADA","local_address":"ROOM 1903, YORK HOUSE, THE LANDMARK, 15 QUEEN'S ROAD, CENTRAL, HONG KONG.","principle_address":"600 DE LA GAUCHETIERE WEST, MONTREAL, QUEBEC, H3B 4L2, CANADA.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"NATIONAL BANK OF PAKISTAN","local_address":"UNIT 1804-05, 18/F, FWD FINANCIAL CENTRE, 308-320 DES VOEUX ROAD CENTRAL, HONG KONG.","principle_address":"I.I. CHUNDRIGAR ROAD, HEAD OFFICE, KARACHI, PAKISTAN.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"NATIXIS","local_address":"UNITS 7101-7103A, 7104-7107A, 7108 ON 71/F AND THE WHOLE OF 72/F, INTERNATIONAL COMMERCE CENTRE, 1 AUSTIN ROAD WEST, KOWLOON.","principle_address":"30, AVENUE PIERRE MENDES- FRANCE- 75013 PARIS FRANCE.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100226"}
{"name":"NATWEST MARKETS PLC","local_address":"UNIT 702, 7/F, LHT TOWER, 31 QUEEN'S ROAD CENTRAL, HONG KONG","principle_address":"36 ST ANDREW SQUARE, EDINBURGH EH2 2YB.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100250"}
{"name":"NIPPON WEALTH LIMITED","local_address":"UNIT 1101-02 & 13B, 11/F, ONE HARBOURFRONT, 18 TAK FUNG STREET, HUNG HOM, KOWLOON","principle_address":null,"type":"Restricted Licence Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=200108"}
{"name":"NISHI-NIPPON CITY BANK, LTD. (THE)","local_address":"SUITE 3112, TOWER 6, THE GATEWAY, HARBOUR CITY, 9 CANTON ROAD, TSIM SHA TSUI, KOWLOON.","principle_address":"3-6 HAKATA-EKIMAE 1-CHOME HAKATA-KU, FUKUOKA-SHI, FUKUOKA-KEN,812-0011, JAPAN.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"NONGHYUP BANK","local_address":"APPROVED BUT NOT YET OPENED","principle_address":"120, TONGIL-RO, JUNG-GU, SEOUL, REPUBLIC OF KOREA","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"NORINCHUKIN BANK (THE)","local_address":"34/F., EDINBURGH TOWER, THE LANDMARK, 15 QUEEN'S ROAD, CENTRAL, HONG KONG.","principle_address":"13-2, YURAKUCHO 1-CHOME, CHIYODA-KU, TOKYO 100-8420, JAPAN.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"O-BANK CO., LTD.","local_address":"SUITES 3210-14, 32/F, TOWER 6, THE GATEWAY, HARBOUR CITY, TSIM SHA TSUI, KOWLOON.","principle_address":"99, SEC.2, TIDING BLVD, NEIHU DISTRICT, TAIPEI, TAIWAN.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"OCBC WING HANG BANK LIMITED","local_address":"161 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100048"}
{"name":"OITA BANK, LTD. (THE)","local_address":"UNIT NO. 1108, 11/F, THE METROPOLIS TOWER, 10 METROPOLIS DRIVE, HUNGHOM, KOWLOON","principle_address":"4-1, FUNAI-CHO 3 CHOME, OITA-SHI, OITA, JAPAN.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"ORIX ASIA LIMITED","local_address":"25TH FLOOR, TWO EXCHANGE SQUARE, 8 CONNAUGHT PLACE, CENTRAL, HONG KONG.","principle_address":null,"type":"Restricted Licence Bank","secstaff_reg_url":null}
{"name":"OVERSEA-CHINESE BANKING CORPORATION LIMITED","local_address":"9/F., NINE QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":"63 CHULIA STREET, #10-00 OCBC CENTRE EAST, SINGAPORE 049514","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100020"}
{"name":"P.T. BANK CENTRAL ASIA","local_address":"UNIT 4707, 47/F, THE CENTER, 99 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":"WILSMA BCA, JL JEND SUDIRMAN KAV 22-23, JAKARTA, INDONESIA.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"P.T. BANK RAKYAT INDONESIA (PERSERO)","local_address":"ROOM 2211, 22/F, LIPPO CENTRE TOWER II, 89 QUEENSWAY, ADMIRALTY, HONG KONG.","principle_address":"JL,JEND. SUDIRMAN NO. 44-46, JAKARTA 10210, INDONESIA.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"PHILIPPINE NATIONAL BANK","local_address":"UNIT 02, 9TH FLOOR, TUNG WAI COMMERCIAL BUILDING, 109-111 GLOUCESTER ROAD, WANCHAI, HONG KONG.","principle_address":"PNB FINANCIAL CENTER, PRES. DIOSDADO MACAPAGAL BLVD., PASAY CITY, PHILIPPINES.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"PICTET & CIE (EUROPE) S.A.","local_address":"9/F, CHATER HOUSE, 8 CONNAUGHT ROAD CENTRAL, CENTRAL, HONG KONG.","principle_address":"15A, AVENUE J.F. KENNEDY, L-1855 LUXEMBOURG.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100312"}
{"name":"PING AN BANK CO., LTD.","local_address":"42/F, ONE EXCHANGE SQUARE, 8 CONNAUGHT PLACE, CENTRAL, HONG KONG","principle_address":"SOUTH TOWER, PING AN FINANCIAL CENTER, 5023 YITIAN ROAD, FUTIAN DISTRICT, SHENZHEN, CHINA","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"PING AN ONECONNECT BANK (HONG KONG) LIMITED","local_address":"ROOM 1903-1904, NEO, 123 HOI BUN ROAD, KWUN TONG, KOWLOON","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":null}
{"name":"PT. BANK MANDIRI (PERSERO) TBK","local_address":"7/F., FAR EAST FINANCE CENTRE, 16 HARCOURT ROAD, HONG KONG.","principle_address":"PLAZA MANDIRI, JL. JEND. GATOT SUBROTO KAV. 36-38, JAKARTA 12190, INDONESIA.","type":"Restricted Licence Bank","secstaff_reg_url":null}
{"name":"PT. BANK NEGARA INDONESIA (PERSERO) TBK.","local_address":"G/F., FAR EAST FINANCE CENTRE, 16 HARCOURT ROAD, CENTRAL, HONG KONG.","principle_address":"J1. JEND. SUDIRMAN KAV. 1, JAKARTA 10220, INDONESIA.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"PUBLIC BANK (HONG KONG) LIMITED","local_address":"PUBLIC BANK CENTRE, 120 DES VOEUX ROAD CENTRAL, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100022"}
{"name":"PUBLIC FINANCE LIMITED","local_address":"ROOM 1105-1107, WING ON HOUSE, 71 DES VOEUX ROAD CENTRAL, CENTRAL DISTRICT, HONG KONG.","principle_address":null,"type":"Deposit-taking Company","secstaff_reg_url":null}
{"name":"PUNJAB NATIONAL BANK","local_address":"1003, 10/F, LI PO CHUN CHAMBERS, 189 DES VOEUX ROAD CENTRAL, HONG KONG.","principle_address":"7, BHIKAJI CAMA PLACE, NEW DELHI, INDIA.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"QATAR NATIONAL BANK (Q.P.S.C.)","local_address":"SUITE 5801-04, 58/F, TWO INTERNATIONAL FINANCE CENTRE, 8 FINANCE STREET, CENTRAL, HONG KONG","principle_address":"P.O. BOX 1000, DOHA, QATAR","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"RESONA BANK, LIMITED","local_address":"SUITES 3402-3404, TWO PACIFIC PLACE, 88 QUEENSWAY, HONG KONG","principle_address":"2-1, BINGOMACHI 2-CHOME, CHUO-KU, OSAKA, JAPAN.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"ROYAL BANK OF CANADA","local_address":"41ST AND 42ND FLOOR, ONE TAIKOO PLACE, TAI KOO PLACE, 979 KING'S ROAD, QUARRY BAY, HONG KONG","principle_address":"200 BAY STREET, TORONTO, ONTARIO, M5J 2J5, CANADA.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100267"}
{"name":"SCOTIABANK (HONG KONG) LIMITED","local_address":"SUITE 2401, CENTRAL TOWER, 28 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":null,"type":"Restricted Licence Bank","secstaff_reg_url":null}
{"name":"SHANGHAI COMMERCIAL & SAVINGS BANK, LTD. (THE)","local_address":"10/F, PENINSULA OFFICE TOWER, 18 MIDDLE ROAD, TSIMSHATSUI, KOWLOON.","principle_address":"2, SEC. 1, MIN CHUAN E. ROAD, TAIPEI, TAIWAN.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100288"}
{"name":"SHANGHAI COMMERCIAL BANK LIMITED","local_address":"SHANGHAI COMMERCIAL BANK TOWER, 12 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100074"}
{"name":"SHANGHAI PUDONG DEVELOPMENT BANK CO., LTD.","local_address":"30/F, SPD BANK TOWER, ONE HENNESSY, 1 HENNESSY ROAD, HONG KONG","principle_address":"12 ZHONGSHAN EAST NO. 1 ROAD, SHANGHAI, CHINA.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100306"}
{"name":"SHIGA BANK, LTD. (THE)","local_address":"UNIT 1001, 10/F, HENLEY BUILDING, 5 QUEEN'S ROAD CENTRAL, HONG KONG","principle_address":"1-38 HAMAMACHI OTSU, SHIGA 520, JAPAN.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"SHINHAN BANK","local_address":"UNIT 7703 ON LEVEL 77, INTERNATIONAL COMMERCE CENTRE, 1 AUSTIN ROAD WEST, KOWLOON.","principle_address":"120, 2GA, TAEPYUNG-RO, JUNG-GU, SEOUL 100-102, KOREA.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100293"}
{"name":"SHINKIN CENTRAL BANK","local_address":"SUITE 4008, 40/F, CENTRAL PLAZA, 18 HARBOUR ROAD, WANCHAI, HONG KONG.","principle_address":"3-7, YAESU 1 CHOME, CHUO-KU, TOKYO 103-0028, JAPAN.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"SHIZUOKA BANK, LTD. (THE)","local_address":"SUITE 1010, 10/F, CHATER HOUSE, 8 CONNAUGHT ROAD CENTRAL, CENTRAL, HONG KONG.","principle_address":"10,GOFUKUCHO 1 CHOME, SHIZUOKA-SHI,SHIZUOKA 420, JAPAN.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"SHOKO CHUKIN BANK, LTD. (THE)","local_address":"SUITE 804, 8/F, CENTRAL PLAZA, 18 HARBOUR ROAD, WANCHAI, HONG KONG.","principle_address":"10-17, YAESU 2-CHOME, CHUO-KU,TOKYO, JAPAN.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"SIAM COMMERCIAL BANK PUBLIC COMPANY LIMITED (THE)","local_address":"SUITE 3209, 32/F, JARDINE HOUSE, 1 CONNAUGHT PLACE, CENTRAL, HONG KONG.","principle_address":"9 RUTCHADAPISEK ROAD, LADYAO, JATUJAK, BANGKOK 10900, THAILAND.","type":"Restricted Licence Bank","secstaff_reg_url":null}
{"name":"SILICON VALLEY BANK","local_address":"SUITE 801, 8/F, JARDINE HOUSE, 1 CONNAUGHT PLACE, CENTRAL, HONG KONG.","principle_address":"3005 TASMAN DRIVE, SANTA CLARA, CA 95054.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"SKANDINAVISKA ENSKILDA BANKEN AB","local_address":"SUITES 1701-1709 AND 1720, 17/F, JARDINE HOUSE, 1 CONNAUGHT PLACE, CENTRAL, HONG KONG.","principle_address":"KUNGSTRADGARDSGATAN 8, 106 40 STOCKHOLM, SWEDEN.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100308"}
{"name":"SOCIETE GENERALE","local_address":"LEVEL 38, THREE PACIFIC PLACE, 1 QUEEN'S ROAD EAST, HONG KONG.","principle_address":"29, BOULEVARD HAUSSMANN, 75009 PARIS, FRANCE.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100102"}
{"name":"STANDARD CHARTERED BANK","local_address":"4-4A DES VOEUX ROAD CENTRAL, HONG KONG.","principle_address":"1 BASINGHALL AVENUE, LONDON EC2V 5DD, UNITED KINGDOM.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"STANDARD CHARTERED BANK (HONG KONG) LIMITED","local_address":"32ND FLOOR, 4-4A DES VOEUX ROAD, CENTRAL, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100269"}
{"name":"STATE BANK OF INDIA","local_address":"15TH FLOOR, CENTRAL TOWER, 28 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":"NARIMAN POINT, BOMBAY 400 021, INDIA.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"STATE STREET BANK AND TRUST COMPANY","local_address":"68TH FLOOR, TWO INTERNATIONAL FINANCE CENTRE, CENTRAL, HONG KONG.","principle_address":"ONE LINCOLN STREET, BOSTON, MA 02111, U.S.A.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100219"}
{"name":"SUMITOMO MITSUI BANKING CORPORATION","local_address":"7/F & 8/F, ONE INTERNATIONAL FINANCE CENTRE, 1 HARBOUR VIEW STREET, CENTRAL, HONG KONG.","principle_address":"1-2, MARUNOUCHI 1-CHOME, CHIYODA-KU, TOKYO, JAPAN.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100078"}
{"name":"SUMITOMO MITSUI TRUST BANK, LIMITED","local_address":"25/F, AIA CENTRAL, 1 CONNAUGHT ROAD CENTRAL, CENTRAL, HONG KONG.","principle_address":"1-4-1, MARUNOUCHI, CHIYODA-KU, TOKYO, 100-8233 JAPAN.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"SVENSKA HANDELSBANKEN AB (PUBL)","local_address":"1608 SUN HUNG KAI CENTRE, 30 HARBOUR ROAD, HONG KONG","principle_address":"KUNGSTRADGARDSGATAN 2, SE-106 70 STOCKHOLM, SWEDEN.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"SWISSQUOTE BANK SA","local_address":"SUITES 3202-04, LEVEL 32, ICBC TOWER, 3 GARDEN ROAD, CENTRAL, HONG KONG.","principle_address":"CHEMIN DE LA CRETAUX 33, CASE POSTALE 391, CH-1196 GLAND, SWITZERLAND.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"TAI SANG BANK LIMITED","local_address":"130-132 DES VOEUX ROAD CENTRAL, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":null}
{"name":"TAI YAU BANK, LIMITED","local_address":"29/F, TAI TUNG BUILDING, 8 FLEMING ROAD, WANCHAI, HONG KONG.","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":null}
{"name":"TAIPEI FUBON COMMERCIAL BANK CO., LTD.","local_address":"16/F, K11 ATELIER, VICTORIA DOCKSIDE, NO. 18 SALISBURY ROAD, TSIM SHA TSUI, KOWLOON","principle_address":"NO.50, SECTION 2, CHUNGSHAN N. ROAD, TAIPEI, TAIWAN.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100257"}
{"name":"TAISHIN INTERNATIONAL BANK CO., LTD","local_address":"6/F & 15/F ROOM NO. 1501-1506, 1510-1511 & 1512A-1512B, TOWER 5, THE GATEWAY, 15 CANTON ROAD, TSIMSHATSUI, KOWLOON.","principle_address":"1-2F, 44 CHUNG SHAN N. RD, SECTION 2, TAIPEI, TAIWAN.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100263"}
{"name":"TAIWAN BUSINESS BANK, LTD.","local_address":"SUITES 2705-9, 27/F, TOWER 6, THE GATEWAY, HARBOUR CITY, KOWLOON.","principle_address":"NO.30 TACHENG STREET, TAIPEI 103, TAIWAN.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"TAIWAN COOPERATIVE BANK, LTD.","local_address":"SUITES 1303-1310, 13/F, EVERBRIGHT CENTRE, 108 GLOUCESTER ROAD, WANCHAI, HONG KONG.","principle_address":"NO.225, SEC. 2, CHANG'AN EAST ROAD, SONG SHAN DIST. TAIPEI CITY 105, TAIWAN (R.O.C)","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"TAIWAN SHIN KONG COMMERCIAL BANK CO., LTD.","local_address":"SUITES 1502-12, 15/F, TOWER 2, THE GATEWAY HARBOUR CITY, 25 CANTON ROAD, TSIMSHATSUI, KOWLOON","principle_address":"21F, NO.32, SONGREN ROAD, XINYI DIST., TAIPEI CITY 110, TAIWAN.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100302"}
{"name":"TORONTO-DOMINION BANK","local_address":"SUITE 1211, TWO PACIFIC PLACE, 88 QUEENSWAY, HONG KONG.","principle_address":"P.O. BOX 1, TORONTO-DOMINION CENTRE, KING ST. W. AND BAY ST., TORONTO, ONTARIO,CANADA M5K 1A2.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100096"}
{"name":"UBS AG","local_address":"52/F, TWO INTERNATIONAL FINANCE CENTRE, 8 FINANCE STREET, CENTRAL, HONG KONG.","principle_address":"AESCHENVORSTADT 1, 4002 BASEL, SWITZERLAND.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100113"}
{"name":"UCO BANK","local_address":"UNIT A & B, 2/F, ASTORIA BUILDING, 34 ASHLEY ROAD, TSIM SHA TSUI, KOWLOON","principle_address":"10 BIPLABI TRAILOKYA MAHARAJ SARANI, (BRABOURNE ROAD) CALCUTTA 700 001, INDIA.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"UNICREDIT BANK AG","local_address":"25/F, MAN YEE BUILDING, 68 DES VOEUX ROAD CENTRAL, HONG KONG.","principle_address":"ARABELLASTRASSE 12, 81925 MUNICH, GERMANY","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100185"}
{"name":"UNION BANCAIRE PRIVÉE, UBP SA","local_address":"26/F, AIA CENTRAL, 1 CONNAUGHT ROAD CENTRAL, CENTRAL, HONG KONG","principle_address":"RUE DU RHONE 96-98, PO BOX 1320, 1211 GENEVA 1, SWITZERLAND","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100321"}
{"name":"UNION BANK OF INDIA","local_address":"UNIT 1903-04, 19/F, NINE QUEEN'S ROAD, CENTRAL, HONG KONG","principle_address":"239, UNION BANK BHAVAN, VIDHAN BHAVAN MARG, NARIMAN POINT, MUMBAI-400021, INDIA.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"UNION BANK OF TAIWAN","local_address":"UNIT 18, 35/F, WEST TOWER, SHUN TAK CENTRE, 200 CONNAUGHT ROAD CENTRAL, HONG KONG.","principle_address":"3F, NO. 109, SECTION 3, MINSHENG E. ROAD, SONGSHAN DISTRICT, TAIPEI CITY 105, TAIWAN","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"UNITED OVERSEAS BANK LTD.","local_address":"28/F, CHAMPION TOWER, 3 GARDEN ROAD, CENTRAL, HONG KONG","principle_address":"80 RAFFLES PLACE, UOB PLAZA, SINGAPORE 0104.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100001"}
{"name":"VIETNAM FINANCE COMPANY LIMITED","local_address":"ROOM 1601, 16/F., GOLDEN STAR BUILDING, 20 LOCKHART ROAD, HONG KONG.","principle_address":null,"type":"Deposit-taking Company","secstaff_reg_url":null}
{"name":"VP BANK LTD","local_address":"SUITE 3305, TWO EXCHANGE SQUARE, 8 CONNAUGHT PLACE, CENTRAL, HONG KONG.","principle_address":"FL-9490 VADUZ, AEULESTRASSE 6, LIECHTENSTEIN.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"WELAB BANK LIMITED","local_address":"23/F, K11 ATELIER KING'S ROAD, 728 KING'S ROAD, QUARRY BAY, HONG KONG","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":null}
{"name":"WELLS FARGO BANK, NATIONAL ASSOCIATION","local_address":"27/F, THREE PACIFIC PLACE, 1 QUEEN'S ROAD EAST, HONG KONG","principle_address":"420 MONTGOMERY STREET, SAN FRANCISCO, CALIFORNIA 94163, USA.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"WESTPAC BANKING CORPORATION","local_address":"16/F, YORK HOUSE, THE LANDMARK, 15 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":"WESTPAC PLACE, LEVEL 18, 275 KENT STREET, SYDNEY, NSW 2000, AUSTRALIA.","type":"Licensed Bank","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=100167"}
{"name":"WOORI BANK","local_address":"SUITE 1401, TWO PACIFIC PLACE, 88 QUEENSWAY, HONG KONG.","principle_address":"1-203, HOEHYON DONG, CHUNG-GU, SEOUL, KOREA.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"WOORI GLOBAL MARKETS ASIA LIMITED","local_address":"ROOMS 1907-1909, 19/F, GLOUCESTER TOWER, THE LANDMARK, 15 QUEEN'S ROAD CENTRAL, HONG KONG.","principle_address":null,"type":"Deposit-taking Company","secstaff_reg_url":"http://apps.hkma.gov.hk/eng/index.php?c=search&m=search_by_institution&ri=300505"}
{"name":"YAMAGUCHI BANK, LTD. (THE)","local_address":"ROOM 403, 4/F FAR EAST FINANCE CENTRE, 16 HARCOURT ROAD, CENTRAL, HONG KONG","principle_address":"2-36, 4-CHOME, TAKEZAKI-CHO, SHIMONOSEKI JAPAN.","type":"Local Representative Office","secstaff_reg_url":null}
{"name":"YUANTA COMMERCIAL BANK CO., LTD","local_address":"ROOM 2508, 25/F, TOWER 1, ADMIRALTY CENTRE, NO. 18 HARCOURT ROAD, HONG KONG","principle_address":"1, 2, 3, 8F., NO.66 & 1F., NO.68, SEC.1, DUNHUA S.ROAD, TAIPEI, TAIWAN.","type":"Licensed Bank","secstaff_reg_url":null}
{"name":"ZA BANK LIMITED","local_address":"UNIT 1301, LEVEL 13, IT STREET, CYBERPORT 3, 100 CYBERPORT ROAD, HONG KONG","principle_address":null,"type":"Licensed Bank","secstaff_reg_url":null}
